# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml
# USE THIS FOR LOCAL DEV apiUrl = "/.redwood/functions"
# USE THIS FOR RENDER apiUrl = "https://ssrtest-api.onrender.com"
[web]
  title = "Redwood App"
  port = 8910
  apiUrl = "https://ssrtest-api.onrender.com"
  includeEnvironmentVariables = ["PROJECT_WEBSITE","SHORT_PROJECT_WEBSITE","SUPABASE_URL","SUPABASE_KEY"]
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]

[experimental.streamingSsr]
  enabled = true
