# Quick links to the docs:
# - Redwood on Render: https://render.com/docs/deploy-redwood
# - Render's Blueprint spec: https://render.com/docs/yaml-spec

services:
  - name: SSRTest-api
    type: web
    plan: free
    env: node
    region: oregon
    buildCommand: corepack enable && yarn && yarn rw build api
    startCommand: yarn rw serve api

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SSRTest-db
          property: connectionString

  - name: SSRTest-web-server
    type: web
    plan: standard
    env: node
    region: oregon
    buildCommand: corepack enable && yarn install && yarn rw build web
    startCommand: yarn rw serve web

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SSRTest-db
          property: connectionString
  - type: redis
    name: redis1
    #ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lfu # optional (defaults to allkeys-lru). Rails recommends allkeys-lfu as a default.
    ipAllowList:
    - source: 0.0.0.0/0 #I wasn't able to get this work using just the internal connection
      description: public
# databases:
#   - name: SSRTest-db
#     region: oregon
