# Quick links to the docs:
# - Redwood on Render: https://render.com/docs/deploy-redwood
# - Render's Blueprint spec: https://render.com/docs/yaml-spec
# was - buildCommand: corepack enable && yarn install && yarn rw deploy render web
services:
- name: SSRTest-web
  type: web
  env: static
  buildCommand: corepack enable && yarn install
  staticPublishPath: ./web/dist

  envVars:
  - key: SKIP_INSTALL_DEPS
    value: true

  routes:
  - type: rewrite
    source: /.redwood/functions/*
    # Replace `destination` here after your first deploy:
    #
    # ```
    # destination: https://my-redwood-project-api.onrender.com/*
    # ```
    destination: https://ssrtest-api.onrender.com/*
  - type: rewrite
    source: /*
    destination: /index.html
- name: SSRTest-api
  type: web
  plan: free
  env: node
  region: oregon
  buildCommand: corepack enable && yarn && yarn rw build api
  startCommand: yarn rw deploy render api

  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: SSRTest-db
      property: connectionString

- name: SSRTest-web-server
    type: web
    plan: free
    env: node
    region: oregon
    buildCommand: corepack enable && yarn install &&  yarn rw build web
    startCommand: yarn rw serve web

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SSRTest-db
          property: connectionString


databases:
  - name: SSRTest-db
    region: oregon
